@HexMaster.BlazorChat.Server_HostAddress = http://localhost:5111

GET {{HexMaster.BlazorChat.Server_HostAddress}}/todos/
Accept: application/json

###

GET {{HexMaster.BlazorChat.Server_HostAddress}}/todos/1
Accept: application/json

###
